service:
  name: encrypt-decrypt-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10

functions:
  encrypt:
    handler: handler.encrypt
    events:
      - http:
          method: get
          path: encrypt
  decrypt:
    handler: handler.decrypt
    events:
      - http:
          method: get
          path: decrypt
